# -*- coding: utf-8 -*-
"""winvoker_model_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKo7oWJOR6GanS9qqmhgKpQkzQH0ZU8O
"""

!pip install torch transformers datasets joblib
!pip install zemberek-python

# ================================
# Winvoker Veri Seti Ön İşleme + BERT Embedding (Colab GPU için)

# Gerekli kütüphaneler
!pip install torch transformers datasets joblib
!pip install zemberek-python

import pandas as pd
import re
from zemberek import TurkishMorphology
import joblib
import torch
from transformers import BertTokenizer, BertModel
from datasets import load_dataset


# Zemberek Başlatma
morphology = TurkishMorphology.create_with_defaults()


# Veri Seti Yükleme
dataset = load_dataset("winvoker/turkish-sentiment-analysis-dataset")
train_df = pd.DataFrame(dataset['train'])
test_df = pd.DataFrame(dataset['test'])


# Ön İşleme Fonksiyonu
def preprocess_text_zemberek(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    words = text.split()
    lemmas = []
    for w in words:
        try:
            result = morphology.lemmatize(w)
            if result:
                lemmas.append(result[0])
            else:
                lemmas.append(w)
        except:
            lemmas.append(w)
    return ' '.join(lemmas), lemmas

# Train ve Test setlerine uygulama
train_df['text'], train_df['tokens'] = zip(*train_df['text'].apply(preprocess_text_zemberek))
test_df['text'], test_df['tokens'] = zip(*test_df['text'].apply(preprocess_text_zemberek))

# İşlenmiş veriyi kaydetme
joblib.dump(train_df, 'processed_train_zemberek.joblib')
joblib.dump(test_df, 'processed_test_zemberek.joblib')

print("Zemberek ile ön işleme tamamlandı ve kaydedildi.")
print("Train set örnek:")
print(train_df.head(5))


# BERT Modeli Yükleme
MODEL_NAME = "dbmdz/bert-base-turkish-cased"
tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)
bert_model = BertModel.from_pretrained(MODEL_NAME)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Kullanılan cihaz:", device)
bert_model.to(device)


# BERT Embedding Fonksiyonu
def get_bert_embeddings(text_list, batch_size=16, max_len=128):
    embeddings = []
    for i in range(0, len(text_list), batch_size):
        batch_texts = text_list[i:i+batch_size]
        encoded = tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt", max_length=max_len)
        encoded = {key: val.to(device) for key, val in encoded.items()}

        with torch.no_grad():
            outputs = bert_model(**encoded)
            batch_embeddings = outputs.last_hidden_state[:, 0, :].cpu()  # CLS token
        embeddings.append(batch_embeddings)
    return torch.cat(embeddings, dim=0)

print("Train için BERT embedding çıkarılıyor...")
train_embeddings = get_bert_embeddings(train_df['text'].tolist(), batch_size=16, max_len=128)

print("Test için BERT embedding çıkarılıyor...")
test_embeddings = get_bert_embeddings(test_df['text'].tolist(), batch_size=16, max_len=128)

# Kaydetme
joblib.dump(train_embeddings, "bert_train_embeddings.joblib")
joblib.dump(test_embeddings, "bert_test_embeddings.joblib")

print("BERT embeddingler kaydedildi.")
print("Train embedding shape:", train_embeddings.shape)
print("Test embedding shape:", test_embeddings.shape)



from google.colab import drive
drive.mount('/content/drive')

# Örnek yol:
train_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_train_embeddings.joblib")
test_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_test_embeddings.joblib")

# Eğer embeddingler torch.Tensor ise numpy'a çevir
train_embeddings = train_embeddings.numpy()
test_embeddings = test_embeddings.numpy()

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Proje"
os.listdir(folder_path)

folder_path = "/content/drive/MyDrive/Proje/Embeddings"
os.listdir(folder_path)

!pip install zemberek-python

from zemberek import TurkishMorphology

# Zemberek başlatma
morphology = TurkishMorphology.create_with_defaults()


# LR

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Model oluşturma
clf = LogisticRegression(max_iter=500, multi_class='multinomial')

# Modeli eğitme
clf.fit(train_embeddings, y_train)

# Test seti ile tahmin
y_pred = clf.predict(test_embeddings)

# Başarıyı ölçme
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import joblib

train_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_train_embeddings.joblib")
test_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_test_embeddings.joblib")


train_df = joblib.load("/content/drive/MyDrive/Proje/Embeddings/processed_train_zemberek.joblib")
test_df = joblib.load("/content/drive/MyDrive/Proje/Embeddings/processed_test_zemberek.joblib")


train_embeddings = train_embeddings.numpy()
test_embeddings = test_embeddings.numpy()


y_train = train_df['label'].values
y_test = test_df['label'].values

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report


# MLP Modeli

mlp = MLPClassifier(
    hidden_layer_sizes=(256, 128),  # iki gizli katman
    activation='relu',              # ReLU aktivasyonu
    solver='adam',                  # Adam optimizasyon
    max_iter=50,                    # iterasyon sayısı
    random_state=42,
    verbose=True
)


mlp.fit(train_embeddings, y_train)
y_pred = mlp.predict(test_embeddings)
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive/Proje/Embeddings"))

import joblib

# Embeddingleri yükle
train_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_train_embeddings.joblib")
test_embeddings = joblib.load("/content/drive/MyDrive/Proje/Embeddings/bert_test_embeddings.joblib")

# DataFrame'leri yükle
train_df = joblib.load("/content/drive/MyDrive/Proje/Embeddings/processed_train_zemberek.joblib")
test_df = joblib.load("/content/drive/MyDrive/Proje/Embeddings/processed_test_zemberek.joblib")

# Eğer embeddingler torch.Tensor ise numpy'a çevirme
train_embeddings = train_embeddings.numpy()
test_embeddings = test_embeddings.numpy()

# Etiketleri ayarlama
y_train = train_df['label'].values
y_test = test_df['label'].values

# SVM

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

svm_linear = LinearSVC(C=1.0, max_iter=5000, dual=False, random_state=42)
svm_linear.fit(train_embeddings, y_train)

y_pred = svm_linear.predict(test_embeddings)

print("Test Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

